---
title: "Heart Attack Risk Prediction. Final Project"
author: "Giselle Rahimi, Pilar Gore, WonJune Lee, Jiwon Jung, Yoon-hye Cho, Sukyoung Yoon"
date: "`r Sys.Date()`"
---

```{r setup, include = FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(modelr)
library(broom)

untidied_dataset <- read_csv("heart_attack_prediction_dataset.csv")

```


```{r}
untidied_dataset <- untidied_dataset %>%
select(Age, Sex, Cholesterol, `Blood Pressure`,`Heart Rate`, `Family History`, `Exercise Hours Per Week`,`Stress Level`, `Sleep Hours Per Day`, `Heart Attack Risk`,`Triglycerides`,`Physical Activity Days Per Week`, `Sedentary Hours Per Day`, `Diet`)
```

```{r}
untidied_dataset <- untidied_dataset %>%
  rename(
    heart_attack_risk = "Heart Attack Risk",
    blood_pressure = "Blood Pressure",
    heart_rate = "Heart Rate",
    family_history = "Family History",
    exercise_hrs_week = "Exercise Hours Per Week",
    stress_level = "Stress Level",
    sedentary_hrs_day = "Sedentary Hours Per Day",
    physical_days_week = "Physical Activity Days Per Week",
    sleep_hrs = "Sleep Hours Per Day",
    age = "Age",
    sex = "Sex",
    cholesterol = "Cholesterol",
    diet = "Diet",
    triglycerides = "Triglycerides"
  )

```

```{r}
no_family_history_dataset <- subset(untidied_dataset, family_history == 0)
```

```{r}
family_history_dataset <- subset(untidied_dataset, family_history == 1)
```


```{r}
no_family_history_dataset <- no_family_history_dataset %>%
  separate(
    col = blood_pressure,
    into = combine("systolic", "diastolic"),
    sep = "/",
    convert = FALSE
  )

```

```{r}
no_family_history_dataset %>%
ggplot() +
  geom_boxplot(mapping = aes(x = factor(heart_attack_risk), y = exercise_hrs_week))+
  labs(title = "PUT TITLE HERE")

```
```{r}
no_family_history_dataset %>%
  group_by(factor(heart_rate)) %>%
    summarize(
    median = median(exercise_hrs_week),
    mean = mean(exercise_hrs_week),
    max = max(exercise_hrs_week),
    min = min(exercise_hrs_week)
  )
```

boxplot -> sleep hours (x axis), heart attack risk (y) (without family history) Only among people without family history!
```{r}
untidied_dataset %>%
  ggplot() +
  geom_boxplot(mapping = aes(x = factor(heart_attack_risk), y = sleep_hrs)) +
  labs(title = "title")
```

```{r}
untidied_dataset %>%
  ggplot() +
  geom_violin(mapping = aes(x = factor(heart_attack_risk), y = sleep_hrs)) +
  labs(title = "title")
```

```{r}
number_sleep_heart <- no_family_history_dataset %>%
  count(sleep_hrs, heart_attack_risk)
```

```{r}
number_sleep_hrs <- no_family_history_dataset %>%
  count(sleep_hrs)
```

```{r}
number_sleep_hrs %>%
  ggplot() +
  geom_line(mapping = aes(x = sleep_hrs, y = n)) 
```
```{r}
number_heart_attack_risk <- no_family_history_dataset %>%
  count(heart_attack_risk)
```

```{r}
number_heart_attack_risk %>%
  ggplot() +
  geom_line(mapping = aes(x = heart_attack_risk, y = n))
```

```{r}
untidied_dataset <- no_family_history_dataset %>%
  mutate(
    count = 
      ifelse(stress_level >= 1 & !(stress_level >=6) & heart_attack_risk == 1, "no stress & risk",
      ifelse(stress_level >= 1 & !(stress_level >=6) & heart_attack_risk == 0, "no stress & no risk",
      ifelse(stress_level >= 6 & heart_attack_risk == 1, "stress & risk",
      ifelse(stress_level >= 6 & heart_attack_risk == 0, "stress and no risk", NA))))
  )
```

```{r}
untidied_dataset %>%
  group_by(factor(count)) %>%
  summarize(n = n())
```


```{r}
no_family_history_dataset %>%
  ggplot()+
  geom_bar(mapping = aes(x = sleep_hrs)) 
```

```{r}
no_family_history_dataset %>%
  group_by(factor(heart_attack_risk)) %>%
  summarize(n = n())
```

```{r}
family_history_dataset %>%
  group_by(factor(heart_attack_risk)) %>%
  summarize(n = n())
```

```{r}
logistic_model <- glm(
heart_attack_risk ~ exercise_hrs_week + sleep_hrs + stress_level,
family = binomial(),
data = no_family_history_dataset
)

```

```{r}
logistic_predictions <- no_family_history_dataset %>%
  add_predictions(
    logistic_model,
    type = "response"
  ) %>%
  mutate(
    outcome = if_else( condition = pred >0.5,
                       true = 1,
                       false = 0)
  )
```

```{r}
logistic_model %>%
  tidy()
```

```{r}

```

```{r}
  untidied_dataset$heart_attack_risk <- as.character(untidied_dataset$heart_attack_risk)

```

 
```{r}

no_family_history_dataset <- no_family_history_dataset %>%
  mutate(
    stress =
      ifelse(stress_level >= 6, "not_stressed",
      ifelse(stress_level >= 1, "stressed", NA
  )))

```

```{r}
  no_family_history_dataset$stressed_or_not <- as.character(no_family_history_dataset$stressed_or_not)

```


```{r}
heart_attack_risk_null <- untidied_dataset %>%
  specify(heart_attack_risk ~ stress_or_not, success = "stressed") %>%
  hypothesize(null ="independence") %>%
  generate(reps = 10000, type = "permute") %>%
  calculate(stat = "diff in props", order = c("stressed", "not_stressed"))

```

```{r}
heart_attack_risk_obs_stat <- no_family_history_dataset %>%
  specify(heart_attack_risk ~ sleep_hrs) %>%
  calculate(stat = "diff in props")
```

```{r}
heart_attack_risk_p_value <- no_family_history_datatset %>%
  get_p_value(obs_stat = heart_attack_risk_obs_stat, direction = "both")
```

